-- Esquema inicial del taller de herrería.
--
-- Refleja exactamente lo que Hibernate venía creando con ddl-auto: update,
-- extraído con pg_dump de la base de datos real para no dejarse nada.
--
-- A partir de aquí el esquema lo manda Flyway, no Hibernate: application.yml
-- pasa a ddl-auto: validate, que comprueba que las entidades y las tablas
-- concuerdan pero no toca nada. Cualquier cambio futuro va en un fichero
-- V2__..., V3__... y así.
--
-- Las restricciones que Hibernate había nombrado solo (ukio49vjba68...) se
-- renombran a algo legible: un error de clave duplicada tiene que decir qué
-- ha chocado.

-- ---------------------------------------------------------------------------
-- Usuarios y sesiones
-- ---------------------------------------------------------------------------

CREATE TABLE usuarios (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          varchar(255) NOT NULL,
    contrasena_hash varchar(255) NOT NULL,
    rol             varchar(255) NOT NULL,
    CONSTRAINT uq_usuario_nombre UNIQUE (nombre),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('TRABAJADOR', 'JEFE'))
);

-- El token vive en base de datos y no en memoria a propósito: el servidor del
-- taller se apaga cada noche y las sesiones tienen que sobrevivir, o cada
-- mañana habría que volver a entrar.
CREATE TABLE tokens_acceso (
    token      varchar(64) PRIMARY KEY,
    creado     timestamp(6) with time zone NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT fk_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- ---------------------------------------------------------------------------
-- Pedidos
-- ---------------------------------------------------------------------------

-- La fecha la pone el servidor al crear y no se edita nunca.
CREATE TABLE pedidos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha       date NOT NULL,
    trabajador  varchar(255) NOT NULL,
    cliente     varchar(255) NOT NULL,
    descripcion varchar(4000) NOT NULL
);

-- ---------------------------------------------------------------------------
-- Trabajos
-- ---------------------------------------------------------------------------

-- Casi todo es opcional porque un trabajo nace como borrador y puede guardarse
-- a medias. La comprobación de que está completo ocurre al enviarlo.
-- La fecha se estampa en ese momento, no al crearlo.
-- horas es numeric y no un decimal de coma flotante: se suman importes de
-- trabajo y no puede haber errores de redondeo.
CREATE TABLE trabajos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado      varchar(255) NOT NULL,
    fecha       date,
    cliente     varchar(255),
    trabajador  varchar(255),
    descripcion varchar(4000),
    materiales  varchar(4000),
    horas       numeric(7, 2),
    CONSTRAINT ck_trabajo_estado CHECK (estado IN ('BORRADOR', 'ENVIADO'))
);

-- ---------------------------------------------------------------------------
-- Albaranes
-- ---------------------------------------------------------------------------

-- Nace de un trabajo ENVIADO y es una copia instantánea: cliente, trabajador,
-- descripción y fotos se copian, de modo que editar el albarán no altera el
-- trabajo ni al revés. Por eso trabajo_id NO es una clave foránea: el albarán
-- es un documento independiente. Que no se pueda borrar el trabajo de origen
-- se comprueba en TrabajoService, no aquí.
CREATE TABLE albaranes (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero               bigint NOT NULL,
    fecha                date NOT NULL,
    cliente              varchar(255) NOT NULL,
    dni_cliente          varchar(255),
    trabajador           varchar(255) NOT NULL,
    descripcion          varchar(4000) NOT NULL,
    firma                bytea,
    firma_tipo_contenido varchar(255),
    trabajo_id           bigint NOT NULL,
    CONSTRAINT uq_albaran_numero UNIQUE (numero),
    CONSTRAINT uq_albaran_trabajo UNIQUE (trabajo_id)
);

-- ---------------------------------------------------------------------------
-- Fotos
-- ---------------------------------------------------------------------------

-- Una sola tabla para las tres entidades, distinguidas por origen_tipo.
--
-- datos es bytea y NO un large object (oid). Con oid, borrar la fila no libera
-- la imagen: se queda huérfana en pg_largeobject y la base de datos crece para
-- siempre. Llegó a pasar. Que la entidad Foto no lleve @Lob es deliberado.
CREATE TABLE fotos (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origen_tipo    varchar(255) NOT NULL,
    origen_id      bigint NOT NULL,
    tipo_contenido varchar(255) NOT NULL,
    datos          bytea NOT NULL,
    CONSTRAINT ck_foto_origen_tipo CHECK (origen_tipo IN ('PEDIDO', 'TRABAJO', 'ALBARAN'))
);

-- Toda consulta a esta tabla filtra por (origen_tipo, origen_id).
CREATE INDEX idx_foto_origen ON fotos (origen_tipo, origen_id);

-- ---------------------------------------------------------------------------
-- Configuración
-- ---------------------------------------------------------------------------

-- Fila única con el contador de albaranes. Serie global, no reinicia por año.
-- El jefe puede reencauzarla desde la aplicación.
CREATE TABLE configuracion (
    id                     bigint PRIMARY KEY,
    proximo_numero_albaran bigint NOT NULL
);
